### ISSUE TITLE
get_feature

### ISSUE THREAD

**Issue by 464hee** [openmedlab/PathoDuet#2]
What method should I use to obtain features similar to CTransPath returned by P1 or P2 models?

**Comment by 464hee** [comment]
@zhangxiaofan101 @Shentl @hsymm

**Comment by Shentl** [comment]
**1. Get and load the model:** 
    If you run our training code and save the checkpoint, the keys in the state_dict will be started with ‘module.base_encoder’ or ‘module.decoder’. And you should get the clean model with “state_dict[k[len("module.base_encoder."):]] = state_dict[k]”
    If you download our released model (already the cleaned model), then just load it as shown in the README.md

**2. Define model.head**
    If you want to get features, use “model.head = nn.Identity()”, and if you want to perform downstream classification tasks, use “model.head = nn.Linear(768, args.num_classes)”.

**3. Get result**
    If you have correctly defined model.head, then use “_, output = model(images)” to get the feature or classification result.

**Note1:** Considering the gap between pathological images and natural images, we do not use a normalize function in data augmentation during training. Therefore, if the data normalization function is used in downstream tasks, the performance will drop significantly

**No data normalization! No data normalization! No data normalization!**

**Note2:**  Do not use main_cls.py，which is from moco-v3. We will update this file in a few days.

**Note3:**  Do not use the output of model.forward_features() and then average the second dim by yourself. That is because when we set global_pool='avg', model.fc_norm will not be nn.Identity() as in the normal ViT

**Note4:**  We recommend using "model = VisionTransformerMoCo(bridge_token=True, global_pool='avg')" which includes our pretext_token in the model. However, you can also use "model = timm.create_model('vit_base_patch16_224', pretrained=False, global_pool='avg')" and directly load the parameters into a regular vit-base/16 model. We have compared these two different methods and found that there is not much difference in the performance of downstream tasks , with the first approach showing a slight advantage over the second one.

**Comment by 464hee** [comment]
I followed the execution in the sample code and got the following error    

super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'bridge_token'

VisionTransformerMoCo no  bridge_token

I removed this parameter, hopefully it's a correct approach。

I've been able to get the features, thanks

##########################################################

from vits import VisionTransformerMoCo
import torch.nn as nn
import torch
# init the model
model = VisionTransformerMoCo( global_pool='avg')
# init the fc layer
model.head  = nn.Identity()
# load checkpoint
checkpoint = torch.load('checkpoint_p2.pth', map_location="cpu")
model.load_state_dict(checkpoint, strict=False)
images = torch.empty(1, 3, 224,224, dtype=torch.float32, device='cpu')
_,output_feat = model(images)
print(output_feat.shape)
# Your own tasks

**Comment by 464hee** [comment]
No data normalization! No data normalization! No data normalization!
Thanks for repeating the reminder, I was wondering if I could follow this and do a simple processing of the image that could be output better by the model：

###############
transforms_img = transforms.Compose([
transforms.CenterCrop((224,224)),
transforms.ToTensor()]
)

**Comment by Shentl** [comment]
> No data normalization! No data normalization! No data normalization! Thanks for repeating the reminder, I was wondering if I could follow this and do a simple processing of the image that could be output better by the model：
> 
> ############### transforms_img = transforms.Compose([ transforms.Resize((224,224)), transforms.ToTensor()] )

Sure, you could use any data augmentation method other than data normalization, such as RandomResizedCrop, RandomHorizontalFlip, etc.

**Comment by Shentl** [comment]
> I followed the execution in the sample code and got the following error
> 
> super().**init**(**kwargs) TypeError: **init**() got an unexpected keyword argument 'bridge_token'


This is our fault, the bridge_token is something in the original code, we will update the model immediately

**Comment by Shentl** [comment]
Thanks for your issue. We are uploading new models to fix the bug, and we recommend you replacing the  key 'bridge_token' with 'pretext_token' to fix it if you don't want to download the new models again.

**Comment by 464hee** [comment]
ok,Thank you for your reply.
